name: Graphs CI
on:
  repository_dispatch:
    types: [graphs]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    steps:
      - name: Generate graphs
        uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
          POSTMARK_SMTP_TOKEN: ${{ secrets.POSTMARK_SMTP_TOKEN }}
          CONFIG_PATH: status/.upptimerc.yml
